# Generated by Django 4.1 on 2022-09-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date_length',
            field=models.CharField(choices=[('1m', '1 Month'), ('3m', '3 Month'), ('6m', '6 Month'), ('1y', '1 Year')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
