# Generated by Django 4.1.1 on 2022-09-13 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0003_budget_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='budget',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgeter.budget'),
        ),
    ]
