# Generated by Django 4.1.1 on 2022-09-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0006_alter_expenses_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='created_by',
        ),
    ]
