# Generated by Django 4.1.1 on 2022-09-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0007_remove_budget_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='total',
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_length',
            field=models.CharField(default='1 month', max_length=100),
        ),
    ]
